SET DBG_FUNC=
SET DBG_STATES=
SET DBG_LOGFILE=

SET DBG_CNTX_INFO=
SET DBG_CNTX_WARN=
SET DBG_CNTX_PROFILE=
SET DBG_CNTX_ERROR=
SET DBG_CNTX_ALL=TRUE

SET DBG_PRIM_INFO=
SET DBG_PRIM_WARN=
SET DBG_PRIM_PROFILE=
SET DBG_PRIM_ERROR=
SET DBG_PRIM_ALL=

SET DBG_TXT_INFO=
SET DBG_TXT_WARN=
SET DBG_TXT_PROFILE=
SET DBG_TXT_ERROR=
SET DBG_TXT_ALL=

SET DBG_ALL_INFO=
SET DBG_ALL_WARN=TRUE
SET DBG_ALL_PROFILE=
SET DBG_ALL_ERROR=TRUE
SET DBG_ALL=


SET MESA_FORCE_SW=
SET MESA_STRETCH_ON=
SET MESA_MIPMAP_OFF=
