##############################################################################
# 
# Mesa-3.0 Makefile for DirectX 6 Driver                             Build 0.75
#
# By Leigh McRae
#
# http://www.altsoftware.com/
#
# Copyright (c) 1999-1998  alt.software inc.  All Rights Reserved     
##############################################################################
NAME=
TARGET= WGL Driver (D3DHAL)

INCLUDE=$(SDKROOT)\include;$(INCLUDE)
LIB=$(SDKROOT)\lib;$(LIB)
##############################################################################
CPPFLAGS= /c /W1 /G5 /GM /Zp4 /I..\ /I..\..\Include \
	/D "_WIN32" /D "WIN32" /D "_WINDOWS" /D "__WIN32__" /D "__MSC__"  /D "MESAD3D" /D "NOCRYPT"

!IF "$(DEBUG)" == "1"

CPPFLAGS=$(CPPFLAGS) /MTd /Od /Z7 /Yd /D "_DEBUG" /D "D3D_DEBUG" 
BUILD_TYPE=debug

!ELSE

CPPFLAGS=$(CPPFLAGS) /MT /Ob2 /Og /Oi /Ot /Oy /Gs /D "NDEBUG" 
BUILD_TYPE=release

!ENDIF
##############################################################################
SRCS= wgl.cpp NULLProcs.cpp D3DInit.cpp D3DRaster.cpp DDrawPROCS.cpp \
	D3DVBRender.cpp D3DTextureMgr.cpp D3DSurface.cpp D3DBitmaps.cpp Debug.cpp
OBJS= $(SRCS:.cpp=.obj)

WINLIBS = kernel32.lib user32.lib gdi32.lib oldnames.lib 
DXLIBS = 
LIBS = $(WINLIBS) $(DXLIBS) 
###############################################################################
# Primary Targets                                                             #
###############################################################################

default: header HAL footer

all: default 

HAL : $(OBJS)

install : forceit
	@echo $(SPACE)
	@echo ========================================
	@echo Install files created.
	@echo ========================================

        
###############################################################################
# Secondary Targets                                                           #
###############################################################################

clean:
	@echo ========================================
	@echo Cleaning $(TARGET)
	@del *.obj 
	@del *.dep 
	@del *.exp 
	@del *.ncb
	@del *.plg
	@del *.lib
	@echo ========================================

header:
	@echo ============================================================
	@echo Building $(TARGET)  ($(BUILD_TYPE) version)
	@echo ============================================================
	@echo $(SPACE)

footer:
	@echo $(SPACE)
	@echo ============================================================
	@echo DONE building $(TARGET)  ($(BUILD_TYPE) version)
	@echo ============================================================

forceit:




